### ISSUE TITLE
[bug] tests aren't 100% working

### ISSUE THREAD

**Issue by niftylettuce** [breejs/later#1]
It seems like there's a timezone offset issue with running the tests versus the original author's timezone (which are hardcoded).  There might be other issues too, e.g. with the original codebase.  I did notice one major issue which I thought stood out, search for "TODO" in the `src/index.js` file to see the comment.

**Comment by jdalrymple** [comment]
Does later take into consideration timezones? Or is it just set to the hardcoded ones like you mentioned above?

**Comment by niftylettuce** [comment]
It seems like this fork of `later` is the culprit behind the issues found in <https://github.com/breejs/bree/issues/29>.

**Comment by niftylettuce** [comment]
Something went wrong with my fork, I'm going to spend a little time here trying to figure it out... If you see anything let me know.

**Comment by niftylettuce** [comment]
I got it figured out, will release shortly.

**Comment by niftylettuce** [comment]
This is now resolved as of v4.0.0.  I am also releasing a new version of bree now.
