### ISSUE TITLE
Difference between `@breejs/later` and `sfn-scheduler-parser`?

### ISSUE THREAD

**Issue by Lioness100** [breejs/later#18]
I don't think breejs quite fits my usecase, but I'd still love to use `@breejs/later` to turn specifically human phrases into programmatically usable dates. In breejs' readme, it lists `sfn-scheduler` as an unmaintained alternative, and cites that its parser doesn't accept crons. However, I don't need support for crons, so I was wondering if there was any big selling point to this library over `sfn-scheduler-parser` relating to text parsing. Thanks!

**Comment by niftylettuce** [comment]
This library was mainly created as a modern and updated version of the original `later` library.

I would compare `later` to `sfn-scheduler-parser` in order to learn more.

**Comment by Lioness100** [comment]
That's what I'm trying to do 🤔

**Comment by niftylettuce** [comment]
Just compare <https://breejs.github.io/later/parsers.html#text> to <https://github.com/hyurl/sfn-schedule-parser#example>.  The syntax / language parsing is slightly different it seems. 

For example `@breejs/later` (and `later` originally) support text like `on the`, and `sfn-scheduler-parser` has different syntax to achieve the same thing.
