### ISSUE TITLE
npm install for 4.1.0 not working on macOS

### ISSUE THREAD

**Issue by nanoamp** [breejs/later#19]
Installing via `npm i @breejs/later` on macOS Monterey, after some time, it completes without error, but I get a _node_modules/@breejs/later_ folder which only has three files - licence, package.json and readme.

If I install with `npm i @breejs/later@4.0.2` then I get a dist and lib folder created as well.

Is this something awry with packaging of _latest_ on the npmjs repo, or is this something client-side that I can provide more info to debug? I'm running npm 8.2.0 at the moment.

**Comment by nanoamp** [comment]
For info, I've tried it on a Pi 3 running npm 6.11.3 as well as npm 8.2.0, and _latest_ installed correctly.

**Comment by niftylettuce** [comment]
I'm unable to reproduce and I'm guessing something was cached on your machine?  What version only had 3 files?

```sh
❯ npm i @breejs/later

+ @breejs/later@4.1.0
added 1 package from 2 contributors and audited 47 packages in 1.388s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

❯ cd node_modules/@breejs/later
❯ ls
dist  lib  LICENSE  package.json  README.md
```

**Comment by nanoamp** [comment]
Sorry, I've changed jobs since I raised this, and don't have access to that Mac any more, so I can't test. I think it's unlikely to have been down to caching though, as it was a first-time install.
