### ISSUE TITLE
Every 5th of September and December

### ISSUE THREAD

**Issue by ranouf** [breejs/later#5]
Hi,

When I execute this code:
      var scheduler = later.parse.recur().on(12).month()
        .and().on(9).month()
        .and().on(5).dayOfMonth();

      later.date.localTime();
      var results = later.schedule(scheduler).next(3);

I was thinking to get:
- 5/12/2020
- 5/9/2021
- 5/12/2021

But I receive:
- 5/11/2020
- 1/12/2020
- 5/12/2020

How to get the expected result?
Thanks

**Comment by ranouf** [comment]
The solution was to remove the and()

**Comment by niftylettuce** [comment]
Ah nice!

You could also do two cron jobs that reference the same `path`, and just duplicate the job definition object with unique `name` values, e.g. `{ path: '...', name: 'september', cron: '0 0 5 9 *' }` and `{ path: '...', name: 'december', cron: '0 0 5 12 *' }` (see https://crontab.guru/#0_0_5_9_*).
